export const columns = [
  { name: "ID", uid: "id" },
  { name: "NAME", uid: "name", sortable: true },
  { name: "ROLE", uid: "role", sortable: true },
  { name: "PHONE", uid: "phone", sortable: true },
  { name: "EMAIL", uid: "mail", sortable: true },
  { name: "STATUS", uid: "status", sortable: true },
];

export const users = [
  {
    id: 1,
    name: "Tony Reichert",
    role: "CEO",
    status: "active",
    phone: "29",
    mail: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    role: "Tech Lead",
    status: "blocked",
    phone: "25",
    mail: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    role: "Sr. Dev",
    status: "active",
    phone: "22",
    mail: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    role: "C.M.",
    status: "blocked",
    phone: "28",
    mail: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    role: "S. Manager",
    status: "active",
    phone: "24",
    mail: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Brian Kim",
    role: "P. Manager",
    status: "active",
    phone: "29",
    mail: "brian.kim@example.com",
  },
  {
    id: 7,
    name: "Michael Hunt",
    role: "Designer",
    status: "blocked",
    phone: "27",
    mail: "michael.hunt@example.com",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    role: "HR Manager",
    status: "active",
    phone: "31",
    mail: "samantha.brooks@example.com",
  },
  {
    id: 9,
    name: "Frank Harrison",
    role: "F. Manager",
    status: "blocked",
    phone: "33",
    mail: "frank.harrison@example.com",
  },
  {
    id: 10,
    name: "Emma Adams",
    role: "Ops Manager",
    status: "active",
    phone: "35",
    mail: "emma.adams@example.com",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    status: "active",
    phone: "22",
    mail: "brandon.stevens@example.com",
  },
  {
    id: 12,
    name: "Megan Richards",
    role: "P. Manager",
    status: "blocked",
    phone: "28",
    mail: "megan.richards@example.com",
  },
  {
    id: 13,
    name: "Oliver Scott",
    role: "S. Manager",
    status: "active",
    phone: "37",
    mail: "oliver.scott@example.com",
  },
  {
    id: 14,
    name: "Grace Allen",
    role: "M. Specialist",
    status: "active",
    phone: "30",
    mail: "grace.allen@example.com",
  },
  {
    id: 15,
    name: "Noah Carter",
    role: "IT Specialist",
    status: "blocked",
    phone: "31",
    mail: "noah.carter@example.com",
  },
  {
    id: 16,
    name: "Ava Perez",
    role: "Manager",
    status: "active",
    phone: "29",
    mail: "ava.perez@example.com",
  },
  {
    id: 17,
    name: "Liam Johnson",
    role: "Data Analyst",
    status: "active",
    phone: "28",
    mail: "liam.johnson@example.com",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    role: "QA Analyst",
    status: "active",
    phone: "27",
    mail: "sophia.taylor@example.com",
  },
  {
    id: 19,
    name: "Lucas Harris",
    role: "Administrator",
    status: "blocked",
    phone: "32",
    mail: "lucas.harris@example.com",
  },
  {
    id: 20,
    name: "Mia Robinson",
    role: "Coordinator",
    status: "active",
    phone: "26",
    mail: "mia.robinson@example.com",
  },
];
