export const featureArray = [
  { featureName: "Find a Store", route: "/retail" },
  { featureName: "Help", route: "/help" },
  { featureName: "Join Us", route: "/membership" },
  { featureName: "Sign In", route: "/login", separator: false },
];

export const mainCategoryArray = [
  {
    mainCategoryName: "New & Featured",
    route: "/retail",
    id: "358779",
    subCategory: [
      {
        subCategoryName: "New & Featured",
        id: "669173",
        tags: [
          { name: "New Arrivals", id: "847214" },
          { name: "Latest Shoes", id: "909758" },
          { name: "Latest Clothing", id: "241804" },
          { name: "Customise with Nike By You", id: "190215" },
          { name: "Bestsellers", id: "350674" },
          { name: "Member Exclusive", id: "570127" },
          { name: "National Team Kits", id: "862402" },
          { name: "Top Kicks Under 3,000,000₫", id: "357594" },
        ],
      },
      {
        subCategoryName: "Shop Icons",
        id: "892196",
        tags: [
          { name: "Air Force 1", id: "992038" },
          { name: "Air Jordan 1", id: "879710" },
          { name: "Air Max", id: "394116" },
          { name: "Dunk", id: "965011" },
          { name: "Cortez", id: "844587" },
          { name: "Blazer", id: "691960" },
          { name: "Pegasus", id: "688281" },
        ],
      },
      {
        subCategoryName: "New For Men",
        id: "755070",
        tags: [
          { name: "Shoes", id: "727059" },
          { name: "Clothing", id: "854129" },
          { name: "Accessories", id: "417986" },
          { name: "Shop All New", id: "856784" },
        ],
      },
      {
        subCategoryName: "New For Women",
        id: "832104",
        tags: [
          { name: "Shoes", id: "209389" },
          { name: "Clothing", id: "183022" },
          { name: "Accessories", id: "505320" },
          { name: "Shop All New", id: "349937" },
        ],
      },
      {
        subCategoryName: "New For Kids",
        id: "104728",
        tags: [
          { name: "Shoes", id: "256327" },
          { name: "Clothing", id: "154638" },
          { name: "Accessories", id: "311940" },
          { name: "Shop All New", id: "975798" },
        ],
      },
    ],
  },
  {
    mainCategoryName: "Men",
    route: "/men",
    id: "234912",
    subCategory: [
      {
        subCategoryName: "Featured",
        id: "573016",
        tags: [
          { name: "New Releases", id: "454364" },
          { name: "Bestsellers", id: "205647" },
          { name: "Member Exclusive", id: "131001" },
          { name: "Jordan", id: "509337" },
          { name: "Lifestyle Running", id: "422553" },
          { name: "Customise with Nike By You", id: "447999" },
          { name: "Sale", id: "182104" },
          { name: "Running Shoe Finder", id: "716666" },
          { name: "Sustainable Materials", id: "362898" },
        ],
      },
      {
        subCategoryName: "Shoes",
        id: "210936",
        tags: [
          { name: "All Shoes", id: "204820" },
          { name: "Newest Sneakers", id: "947260" },
          { name: "Jordan", id: "271746" },
          { name: "Lifestyle", id: "153498" },
          { name: "Running", id: "726408" },
          { name: "Gym and Training", id: "317416" },
          { name: "Basketball", id: "536359" },
          { name: "Football", id: "930245" },
          { name: "Sandals and Slides", id: "989088" },
          { name: "Last Sizes Available", id: "142613" },
          { name: "Customise with Nike By You", id: "292131" },
          { name: "Top Kicks Under 3,000,000₫", id: "205610" },
        ],
      },
      {
        subCategoryName: "Clothing",
        id: "633825",
        tags: [
          { name: "All Clothing", id: "982861" },
          { name: "Tops and T-Shirts", id: "116965" },
          { name: "Shorts", id: "762278" },
          { name: "Pants and Leggings", id: "398596" },
          { name: "Hoodies and Sweatshirts", id: "661073" },
          { name: "Jackets and Gilets", id: "137043" },
          { name: "Jerseys and Kits", id: "232629" },
          { name: "Jordan", id: "664999" },
        ],
      },
      {
        subCategoryName: "Shop By Sport",
        id: "618725",
        tags: [
          { name: "Running", id: "330993" },
          { name: "Basketball", id: "682781" },
          { name: "Football", id: "360697" },
          { name: "Golf", id: "267118" },
          { name: "Tennis", id: "739791" },
          { name: "Gym and Training", id: "775007" },
          { name: "Yoga", id: "172535" },
          { name: "Skateboarding", id: "457723" },
        ],
      },
      {
        subCategoryName: "Jordan",
        id: "379808",
        tags: [
          { name: "All Jordan", id: "682812" },
          { name: "New Jordan", id: "124740" },
          { name: "Jordan Shoes", id: "481179" },
          { name: "Jordan Clothing", id: "621202" },
          { name: "Jordan Basketball", id: "189700" },
          { name: "Jordan Lifestyle", id: "695237" },
        ],
      },
      {
        subCategoryName: "Accessories and Equipment",
        id: "622872",
        tags: [
          { name: "All Accessories and Equipment", id: "138482" },
          { name: "Bags and Backpacks", id: "921871" },
          { name: "Socks", id: "140736" },
          { name: "Hats and Headwear", id: "737603" },
        ],
      },
      {
        subCategoryName: "Shop By Brand",
        id: "808133",
        tags: [
          { name: "Nike Sportswear", id: "633376" },
          { name: "NikeLab", id: "788788" },
          { name: "Nike By You", id: "695376" },
          { name: "Jordan", id: "234143" },
          { name: "ACG", id: "492266" },
          { name: "NBA", id: "698187" },
          { name: "Nike SB", id: "159366" },
        ],
      },
    ],
  },
  {
    mainCategoryName: "Women",
    route: "/women",
    id: "254119",
    subCategory: [
      {
        subCategoryName: "Featured",
        id: "968171",
        tags: [
          { name: "New Releases", id: "317682" },
          { name: "Bestsellers", id: "110394" },
          { name: "Member Exclusive", id: "181227" },
          { name: "Jordan", id: "238098" },
          { name: "Lifestyle Running", id: "605765" },
          { name: "Customise with Nike By You", id: "179407" },
          { name: "Sale", id: "242376" },
          { name: "Running Shoe Finder", id: "974630" },
          { name: "Sustainable Materials", id: "598496" },
        ],
      },
      {
        subCategoryName: "Shoes",
        id: "492234",
        tags: [
          { name: "All Shoes", id: "149974" },
          { name: "Newest Sneakers", id: "486204" },
          { name: "Jordan", id: "872261" },
          { name: "Lifestyle", id: "620019" },
          { name: "Running", id: "971967" },
          { name: "Gym and Training", id: "425701" },
          { name: "Basketball", id: "498982" },
          { name: "Football", id: "309683" },
          { name: "Sandals and Slides", id: "585299" },
          { name: "Last Sizes Available", id: "130142" },
          { name: "Customise with Nike By You", id: "981869" },
          { name: "Top Kicks Under 3,000,000₫", id: "153189" },
        ],
      },
      {
        subCategoryName: "Clothing",
        id: "907694",
        tags: [
          { name: "All Clothing", id: "775319" },
          { name: "Tops and T-Shirts", id: "451525" },
          { name: "Shorts", id: "780650" },
          { name: "Pants and Leggings", id: "931084" },
          { name: "Hoodies and Sweatshirts", id: "996914" },
          { name: "Jackets and Gilets", id: "999313" },
          { name: "Jerseys and Kits", id: "747081" },
          { name: "Jordan", id: "481186" },
        ],
      },
      {
        subCategoryName: "Shop By Sport",
        id: "495227",
        tags: [
          { name: "Running", id: "252126" },
          { name: "Basketball", id: "178457" },
          { name: "Football", id: "860622" },
          { name: "Golf", id: "183392" },
          { name: "Tennis", id: "718419" },
          { name: "Gym and Training", id: "526919" },
          { name: "Yoga", id: "176320" },
          { name: "Skateboarding", id: "361754" },
        ],
      },
      {
        subCategoryName: "Accessories and Equipment",
        id: "143918",
        tags: [
          { name: "All Accessories and Equipment", id: "677080" },
          { name: "Bags and Backpacks", id: "469218" },
          { name: "Socks", id: "710349" },
          { name: "Hats and Headwear", id: "221564" },
        ],
      },
      {
        subCategoryName: "Shop By Brand",
        id: "578780",
        tags: [
          { name: "Nike Sportswear", id: "720739" },
          { name: "NikeLab", id: "570539" },
          { name: "Nike By You", id: "370238" },
          { name: "Jordan", id: "616336" },
          { name: "ACG", id: "852409" },
          { name: "NBA", id: "414491" },
          { name: "Nike SB", id: "249264" },
        ],
      },
    ],
  },
  {
    mainCategoryName: "Kids",
    route: "/",
    id: "721104",
    subCategory: [
      {
        subCategoryName: "Featured",
        id: "336259",
        tags: [
          { name: "New Releases", id: "430339" },
          { name: "Bestsellers", id: "806942" },
          { name: "Member Exclusive", id: "196888" },
          { name: "Jordan", id: "882090" },
          { name: "Lifestyle Running", id: "761307" },
          { name: "Customise with Nike By You", id: "189059" },
          { name: "Sale", id: "760623" },
          { name: "Running Shoe Finder", id: "439883" },
          { name: "Sustainable Materials", id: "684946" },
        ],
      },
      {
        subCategoryName: "Boys' Shoes",
        id: "273896",
        tags: [
          { name: "All Shoes", id: "353633" },
          { name: "Older Boys (7 - 14 years)", id: "801605" },
          { name: "Younger Boys (4 - 7 years)", id: "847664" },
          { name: "Babies and Toddlers (0 - 4 years)", id: "222186" },
          { name: "Lifestyle", id: "861829" },
          { name: "Jordan", id: "690598" },
          { name: "Running", id: "586217" },
          { name: "Basketball", id: "216912" },
          { name: "Football", id: "234305" },
          { name: "Sandals and Slides", id: "566264" },
        ],
      },
      {
        subCategoryName: "Girls' Shoes",
        id: "946253",
        tags: [
          { name: "All Shoes", id: "252405" },
          { name: "Older Girls (7 - 14 years)", id: "865750" },
          { name: "Younger Girls (4 - 7 years)", id: "336073" },
          { name: "Babies and Toddlers (0 - 4 years)", id: "759418" },
          { name: "Lifestyle", id: "111872" },
          { name: "Jordan", id: "348960" },
          { name: "Running", id: "128850" },
          { name: "Basketball", id: "675957" },
          { name: "Football", id: "298243" },
          { name: "Sandals and Slides", id: "181660" },
        ],
      },
      {
        subCategoryName: "Accessories and Equipment",
        id: "229113",
        tags: [
          { name: "All Accessories and Equipment", id: "954630" },
          { name: "Bags and Backpacks", id: "835648" },
          { name: "Socks", id: "814256" },
          { name: "Hats and Headwear", id: "726268" },
        ],
      },
      {
        subCategoryName: "Kids By Age",
        id: "225520",
        tags: [
          { name: "Older Kids (7 - 14 years)", id: "198591" },
          { name: "Younger Kids (4 - 7 years)", id: "149118" },
          { name: "Babies & Toddlers (0 - 4 years)", id: "372645" },
        ],
      },
      {
        subCategoryName: "Boys' Clothing",
        id: "745119",
        tags: [
          { name: "Tops and T-Shirts", id: "399975" },
          { name: "Hoodies and Sweatshirts", id: "698997" },
          { name: "Pants and Leggings", id: "265160" },
          { name: "Shorts", id: "352154" },
          { name: "All Boys' Clothing", id: "144128" },
        ],
      },
      {
        subCategoryName: "Girls' Clothing",
        id: "527873",
        tags: [
          { name: "Tops and T-Shirts", id: "428857" },
          { name: "Sports Bra", id: "738826" },
          { name: "Hoodies and Sweatshirts", id: "232765" },
          { name: "Pants and Leggings", id: "956114" },
          { name: "Shorts", id: "508210" },
          { name: "All Boys' Clothing", id: "818083" },
        ],
      },
      {
        subCategoryName: "Shop By Brand",
        id: "642442",
        tags: [
          { name: "Nike Sportswear", id: "904054" },
          { name: "NikeLab", id: "903321" },
          { name: "Nike By You", id: "876060" },
          { name: "Jordan", id: "339648" },
          { name: "ACG", id: "368453" },
          { name: "NBA", id: "148074" },
          { name: "Nike SB", id: "715126" },
        ],
      },
    ],
  },
  {
    mainCategoryName: "Sale",
    route: "/sale",
    id: "130261",
    subCategory: [
      {
        subCategoryName: "Shop All Sale",
        id: "365130",
        tags: [
          { name: "Men's Sale", id: "986644" },
          { name: "Women's Sale", id: "531088" },
          { name: "Kids' Sale", id: "843553" },
        ],
      },
      {
        subCategoryName: "Men's Sale",
        id: "189885",
        tags: [
          { name: "Shoes", id: "418101" },
          { name: "Clothing", id: "150183" },
          { name: "Accessories", id: "368089" },
        ],
      },
      {
        subCategoryName: "Women's Sale",
        id: "722693",
        tags: [
          { name: "Shoes", id: "114026" },
          { name: "Clothing", id: "331172" },
          { name: "Accessories", id: "927982" },
        ],
      },
      {
        subCategoryName: "Kids' Sale",
        id: "313060",
        tags: [
          { name: "Shoes", id: "185620" },
          { name: "Clothing", id: "104735" },
          { name: "Accessories", id: "766482" },
        ],
      },
    ],
  },
  { mainCategoryName: "Customize", route: "/nike-by-you" },
  { mainCategoryName: "SNKRS" },
];

// [
//   {
//     mainCategoryName: "New & Featured",
//     route: "/retail",
//     subCategory: [
//       {
//         subCategoryName: "New & Featured",
//         tags: [
//           { name: "New Arrivals" },
//           { name: "Latest Shoes" },
//           { name: "Latest Clothing" },
//           { name: "Customise with Nike By You" },
//           { name: "Bestsellers" },
//           { name: "Member Exclusive" },
//           { name: "National Team Kits" },
//           { name: "Top Kicks Under 3,000,000₫" },
//         ],
//       },
//       {
//         subCategoryName: "Shop Icons",
//         tags: [
//           { name: "Air Force 1" },
//           { name: "Air Jordan 1" },
//           { name: "Air Max" },
//           { name: "Dunk" },
//           { name: "Cortez" },
//           { name: "Blazer" },
//           { name: "Pegasus" },
//         ],
//       },
//       {
//         subCategoryName: "New For Men",
//         tags: [{ name: "Shoes" }, { name: "Clothing" }, { name: "Accessories" }, { name: "Shop All New" }],
//       },
//       {
//         subCategoryName: "New For Women",
//         tags: [{ name: "Shoes" }, { name: "Clothing" }, { name: "Accessories" }, { name: "Shop All New" }],
//       },
//       {
//         subCategoryName: "New For Kids",
//         tags: [{ name: "Shoes" }, { name: "Clothing" }, { name: "Accessories" }, { name: "Shop All New" }],
//       },
//     ],
//   },
//   {
//     mainCategoryName: "Men",
//     route: "/men",
//     subCategory: [
//       {
//         subCategoryName: "Featured",
//         tags: [
//           { name: "New Releases" },
//           { name: "Bestsellers" },
//           { name: "Member Exclusive" },
//           { name: "Jordan" },
//           { name: "Lifestyle Running" },
//           { name: "Customise with Nike By You" },
//           { name: "Sale" },
//           { name: "Running Shoe Finder" },
//           { name: "Sustainable Materials" },
//         ],
//       },
//       {
//         subCategoryName: "Shoes",
//         tags: [
//           { name: "All Shoes" },
//           { name: "Newest Sneakers" },
//           { name: "Jordan" },
//           { name: "Lifestyle" },
//           { name: "Running" },
//           { name: "Gym and Training" },
//           { name: "Basketball" },
//           { name: "Football" },
//           { name: "Sandals and Slides" },
//           { name: "Last Sizes Available" },
//           { name: "Customise with Nike By You" },
//           { name: "Top Kicks Under 3,000,000₫" },
//         ],
//       },
//       {
//         subCategoryName: "Clothing",
//         tags: [
//           { name: "All Clothing" },
//           { name: "Tops and T-Shirts" },
//           { name: "Shorts" },
//           { name: "Pants and Leggings" },
//           { name: "Hoodies and Sweatshirts" },
//           { name: "Jackets and Gilets" },
//           { name: "Jerseys and Kits" },
//           { name: "Jordan" },
//         ],
//       },
//       {
//         subCategoryName: "Shop By Sport",
//         tags: [
//           { name: "Running" },
//           { name: "Basketball" },
//           { name: "Football" },
//           { name: "Golf" },
//           { name: "Tennis" },
//           { name: "Gym and Training" },
//           { name: "Yoga" },
//           { name: "Skateboarding" },
//         ],
//       },
//       {
//         subCategoryName: "Jordan",
//         tags: [
//           { name: "All Jordan" },
//           { name: "New Jordan" },
//           { name: "Jordan Shoes" },
//           { name: "Jordan Clothing" },
//           { name: "Jordan Basketball" },
//           { name: "Jordan Lifestyle" },
//         ],
//       },
//       {
//         subCategoryName: "Accessories and Equipment",
//         tags: [
//           { name: "All Accessories and Equipment" },
//           { name: "Bags and Backpacks" },
//           { name: "Socks" },
//           { name: "Hats and Headwear" },
//         ],
//       },
//       {
//         subCategoryName: "Shop By Brand",
//         tags: [
//           { name: "Nike Sportswear" },
//           { name: "NikeLab" },
//           { name: "Nike By You" },
//           { name: "Jordan" },
//           { name: "ACG" },
//           { name: "NBA" },
//           { name: "Nike SB" },
//         ],
//       },
//     ],
//   },
//   {
//     mainCategoryName: "Women",
//     route: "/women",
//     subCategory: [
//       {
//         subCategoryName: "Featured",
//         tags: [
//           { name: "New Releases" },
//           { name: "Bestsellers" },
//           { name: "Member Exclusive" },
//           { name: "Jordan" },
//           { name: "Lifestyle Running" },
//           { name: "Customise with Nike By You" },
//           { name: "Sale" },
//           { name: "Running Shoe Finder" },
//           { name: "Sustainable Materials" },
//         ],
//       },
//       {
//         subCategoryName: "Shoes",
//         tags: [
//           { name: "All Shoes" },
//           { name: "Newest Sneakers" },
//           { name: "Jordan" },
//           { name: "Lifestyle" },
//           { name: "Running" },
//           { name: "Gym and Training" },
//           { name: "Basketball" },
//           { name: "Football" },
//           { name: "Sandals and Slides" },
//           { name: "Last Sizes Available" },
//           { name: "Customise with Nike By You" },
//           { name: "Top Kicks Under 3,000,000₫" },
//         ],
//       },
//       {
//         subCategoryName: "Clothing",
//         tags: [
//           { name: "All Clothing" },
//           { name: "Tops and T-Shirts" },
//           { name: "Shorts" },
//           { name: "Pants and Leggings" },
//           { name: "Hoodies and Sweatshirts" },
//           { name: "Jackets and Gilets" },
//           { name: "Jerseys and Kits" },
//           { name: "Jordan" },
//         ],
//       },
//       {
//         subCategoryName: "Shop By Sport",
//         tags: [
//           { name: "Running" },
//           { name: "Basketball" },
//           { name: "Football" },
//           { name: "Golf" },
//           { name: "Tennis" },
//           { name: "Gym and Training" },
//           { name: "Yoga" },
//           { name: "Skateboarding" },
//         ],
//       },
//       {
//         subCategoryName: "Accessories and Equipment",
//         tags: [
//           { name: "All Accessories and Equipment" },
//           { name: "Bags and Backpacks" },
//           { name: "Socks" },
//           { name: "Hats and Headwear" },
//         ],
//       },
//       {
//         subCategoryName: "Shop By Brand",
//         tags: [
//           { name: "Nike Sportswear" },
//           { name: "NikeLab" },
//           { name: "Nike By You" },
//           { name: "Jordan" },
//           { name: "ACG" },
//           { name: "NBA" },
//           { name: "Nike SB" },
//         ],
//       },
//     ],
//   },
//   {
//     mainCategoryName: "Kids",
//     route: "/",
//     subCategory: [
//       {
//         subCategoryName: "Featured",
//         tags: [
//           { name: "New Releases" },
//           { name: "Bestsellers" },
//           { name: "Member Exclusive" },
//           { name: "Jordan" },
//           { name: "Lifestyle Running" },
//           { name: "Customise with Nike By You" },
//           { name: "Sale" },
//           { name: "Running Shoe Finder" },
//           { name: "Sustainable Materials" },
//         ],
//       },
//       {
//         subCategoryName: "Boys' Shoes",
//         tags: [
//           { name: "All Shoes" },
//           { name: "Older Boys (7 - 14 years)" },
//           { name: "Younger Boys (4 - 7 years)" },
//           { name: "Babies and Toddlers (0 - 4 years)" },
//           { name: "Lifestyle" },
//           { name: "Jordan" },
//           { name: "Running" },
//           { name: "Basketball" },
//           { name: "Football" },
//           { name: "Sandals and Slides" },
//         ],
//       },

//       {
//         subCategoryName: "Girls' Shoes",
//         tags: [
//           { name: "All Shoes" },
//           { name: "Older Girls (7 - 14 years)" },
//           { name: "Younger Girls (4 - 7 years)" },
//           { name: "Babies and Toddlers (0 - 4 years)" },
//           { name: "Lifestyle" },
//           { name: "Jordan" },
//           { name: "Running" },
//           { name: "Basketball" },
//           { name: "Football" },
//           { name: "Sandals and Slides" },
//         ],
//       },
//       {
//         subCategoryName: "Accessories and Equipment",
//         tags: [
//           { name: "All Accessories and Equipment" },
//           { name: "Bags and Backpacks" },
//           { name: "Socks" },
//           { name: "Hats and Headwear" },
//         ],
//       },
//       {
//         subCategoryName: "Kids By Age",
//         tags: [
//           { name: "Older Kids (7 - 14 years)" },
//           { name: "Younger Kids (4 - 7 years)" },
//           { name: "Babies & Toddlers (0 - 4 years)" },
//         ],
//       },

//       {
//         subCategoryName: "Boys' Clothing",
//         tags: [
//           { name: "Tops and T-Shirts" },
//           { name: "Hoodies and Sweatshirts" },
//           { name: "Pants and Leggings" },
//           { name: "Shorts" },
//           { name: "All Boys' Clothing" },
//         ],
//       },
//       {
//         subCategoryName: "Girls' Clothing",
//         tags: [
//           { name: "Tops and T-Shirts" },
//           { name: "Sports Bra" },
//           { name: "Hoodies and Sweatshirts" },
//           { name: "Pants and Leggings" },
//           { name: "Shorts" },
//           { name: "All Boys' Clothing" },
//         ],
//       },
//       {
//         subCategoryName: "Shop By Sport",
//         tags: [{ name: "Football" }, { name: "Running" }, { name: "Basketball" }, { name: "Tennis" }],
//       },
//     ],
//   },
//   {
//     mainCategoryName: "Sale",
//     route: "/sales",
//     subCategory: [
//       {
//         subCategoryName: "Sale",
//         tags: [
//           { name: "Shop All Sale" },
//           { name: "Shoes Sale" },
//           { name: "Clothing Sale" },
//           { name: "Accessories & Equipment Sale" },
//         ],
//       },
//       { subCategoryName: "Men's Sale", tags: [{ name: "Shoes" }, { name: "Clothing" }] },
//       { subCategoryName: "Women's Sale", tags: [{ name: "Shoes" }, { name: "Clothing" }] },
//       { subCategoryName: "Kid's Sale", tags: [{ name: "Shoes" }, { name: "Clothing" }] },
//     ],
//   },
//   { mainCategoryName: "Customize", route: "/nike-by-you" },
//   { mainCategoryName: "SNKRS" },
// ];
